############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Running?"
url = "/running"
weight = 3
hasChildren = true

[[main]]
parent = "Running?"
name = "Getting Started"
url = "/running"
weight = 1

[[main]]
parent = "Running?"
name = "The Pledge"
url = "/running/pledge"
weight = 2

[[main]]
name = "Candidates"
url = "/candidates"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "The Pledge"
url = "/pledge"
weight = 2

[[footer]]
name = "Elements"
url = "/elements"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy"
weight = 4
